yatube/about/urls.py
from django.urls import path
from . import views

# app_name обязательно, без него не работает namespace
app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path("create/", views.post_create, name='post_create'),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'
         ),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    # запуск debug toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    # отображение изображений в режиме Debug
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.constraints import UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст публикации',
        help_text='Введите текст публикации',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        db_index=True
    )
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        # Если из таблицы User будет удалён пользователь, то будут удалены
        # все связанные с ним посты
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор публикации',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='g_posts',
        verbose_name='Группа публикации',
        help_text='Укажите группу публикации',
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        verbose_name='Изображение',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Добавьте картинку к публикации',
    )

    class Meta:
        ordering = ['-pub_date', ]

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Пост, к которому оставлен комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        max_length=1000,
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации комментария',
        help_text='Введите текст комментария',
        auto_now_add=True,
        db_index=True
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text


class Follow(models.Model):
    # кто подписывается
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        blank=True, null=True,
    )
    # на кого подписываются
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        blank=True, null=True,
    )

    class Meta:
        UniqueConstraint(fields=['user', 'author'], name='unique_follower')

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа поста',
            'image': 'Картинка поста',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .models import Group, Post, User, Follow
from .forms import PostForm, CommentForm

PAGE_POSTS = 10


def pagination(request, queryset):
    paginator = Paginator(queryset, PAGE_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'paginator': paginator,
        'page_namber': page_number,
        'page_obj': page_obj,
    }


@cache_page(20, key_prefix='index_page', )
def index(request):
    """ Главная страница """
    posts = Post.objects.all()
    paginator = Paginator(posts, PAGE_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
        'posts': posts,
        'title': 'Последние обновления на сайте',
    }
    return render(request, template, context)


def group_posts(request, slug):
    """ Посты в группе """
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.g_posts.all()
    paginator = Paginator(posts, PAGE_POSTS)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        'group': group,
        'posts': posts,
        'title': slug,
    }
    return render(request, template, context)


def profile(request, username):
    """ профайл автора """
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    count = author.posts.count()
    paginator = Paginator(posts, PAGE_POSTS)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(user=request.user,
                                          author=author).exists()
    context = {
        "page_obj": page_obj,
        "count": count,
        "author": author,
        "following": following,
    }
    template = "posts/profile.html"
    return render(request, template, context)


def post_detail(request, post_id):
    """ пост подробно """
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.all()
    post_title = post.text
    count = post.author.posts.count()
    author = post.author
    author_posts = author.posts.all().count()
    template = "posts/post_detail.html"
    context = {
        "post": post,
        "post_title": post_title,
        "author": author,
        "author_posts": author_posts,
        "form": form,
        "comments": comments,
        "count": count,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """ создание нового поста """
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.method == "POST":
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
    groups = Group.objects.all()
    template = "posts/create_post.html"
    context = {"form": form, "groups": groups}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    """ редактирование поста """
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    groups = Group.objects.all()
    if request.user != author:
        return redirect("posts:post_detail", post_id)
    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None,
    )
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    template = "posts/create_post.html"
    context = {
        "form": form,
        "is_edit": is_edit,
        "post": post,
        "groups": groups,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    """ добавление комментария к посту"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """ Главная страница с постами авторов на кого подписался"""
    post_list = Post.objects.filter(author__following__user=request.user)
    context = pagination(request, post_list)
    template = 'posts/follow.html'
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """ подписаться на автора"""
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """ отписаться от автора """
    Follow.objects.filter(user=request.user,
                          author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/includes/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
  <h5 class="card-header">Добавить комментарий:</h5>
  <div class="card-body">
    <form method="post" action="{% url 'posts:add_comment' post.id %}">
      {% csrf_token %}
      <div class="form-group mb-2">
        {{ form.text|addclass:"form-control" }}
      </div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
  </div>
</div>
{% endif %}

{% for comment in comments %}
<div class="media mb-4">
  <div class="media-body">
    <h5 class="mt-0">
      <a href="{% url 'posts:profile' comment.author.username %}">
        {{ comment.author.username }}
      </a>
      <br>
      <a>комментарий создан  {{comment.created|date:"d E Y"}} </a>
    </h5>
    <p>{{ comment.text }}</p>
  </div>
</div>
{% endfor %}

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
 <footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
 </footer>

yatube/templates/includes/form.html
<form method="post" enctype="multipart/form-data">
  {% load user_filters %}
  {% csrf_token %}
  {% for field in form %}
  <div class="form-group row my-3">
    <label for="{{ field.id_for_label }}-help" class="form-text text-muted">
      {{ field.label }}
      <span class="required text-danger">*</span>
    </label>
    <div>
      {{ field|addclass:'form-control' }}
      {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
      {% endif %}
    </div>
  </div>
  {% endfor %}
  <div class="d-flex justify-content-end">
    <button type="submit" class="btn btn-primary">
      {% if is_edit %}Сохранить{% else %}Добавить{% endif %}
    </button>
  </div>
</form>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30"
           class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    {% comment %}
    Меню - список пунктов со стандартными классами Bootsrap.
    Класс nav-pills нужен для выделения активных пунктов
    {% endcomment %}
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:author' %}
        active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
           href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% comment %} Проверка на аудентификацию {% endcomment %}
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link"
           href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light
          {% if view_name == 'users:password_change_form' %}active{% endif %}"
           href="{% url 'users:password_change_form' %}">Изменить пароль</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:logout' %}
        active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li>
       <a href="{% url 'posts:profile' user.username %}">
        Пользователь: {{ user.username }}</a>
      <li>
        {% else %}
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:login' %}
        active{% endif %}" href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:signup' %}
        active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/includes/post.html
<!-- Карточка поста выделена в отдельный файл -->
{% load thumbnail %}
<p>
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
</ul>
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
<img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
{{ post.text|linebreaksbr }}
</p>
{% if request.user == post.author %}
<a href="{% url 'posts:post_edit' post.id %}">Редактировать пост</a>
{% else %}
<a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
{% endif %}
<br>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}