yatube/about/urls.py
from django.urls import path
from . import views

# app_name обязательно, без него не работает namespace
app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path("create/", views.post_create, name='post_create'),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'
         ),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    # запуск debug toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    # отображение изображений в режиме Debug
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.constraints import UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст публикации',
        help_text='Введите текст публикации',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        db_index=True
    )
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        # Если из таблицы User будет удалён пользователь, то будут удалены
        # все связанные с ним посты
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор публикации',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='g_posts',
        verbose_name='Группа публикации',
        help_text='Укажите группу публикации',
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        verbose_name='Изображение',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Добавьте картинку к публикации',
    )

    class Meta:
        ordering = ['-pub_date', ]

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Пост, к которому оставлен комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        max_length=1000,
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации комментария',
        help_text='Введите текст комментария',
        auto_now_add=True,
        db_index=True
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text


class Follow(models.Model):
    # кто подписывается
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        blank=True, null=True,
    )
    # на кого подписываются
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        blank=True, null=True,
    )

    class Meta:
        UniqueConstraint(fields=['user', 'author'], name='unique_follower')

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа поста',
            'image': 'Картинка поста',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .models import Group, Post, User, Follow
from .forms import PostForm, CommentForm

PAGE_POSTS = 10


def pagination(request, queryset):
    paginator = Paginator(queryset, PAGE_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'paginator': paginator,
        'page_namber': page_number,
        'page_obj': page_obj,
    }


@cache_page(20, key_prefix='index_page', )
def index(request):
    """ Главная страница """
    posts = Post.objects.all()
    paginator = Paginator(posts, PAGE_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
        'posts': posts,
        'title': 'Последние обновления на сайте',
    }
    return render(request, template, context)


def group_posts(request, slug):
    """ Посты в группе """
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.g_posts.all()
    paginator = Paginator(posts, PAGE_POSTS)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        'group': group,
        'posts': posts,
        'title': slug,
    }
    return render(request, template, context)


def profile(request, username):
    """ профайл автора """
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    count = author.posts.count()
    paginator = Paginator(posts, PAGE_POSTS)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(user=request.user,
                                          author=author).exists()
    context = {
        "page_obj": page_obj,
        "count": count,
        "author": author,
        "following": following,
    }
    template = "posts/profile.html"
    return render(request, template, context)


def post_detail(request, post_id):
    """ пост подробно """
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.all()
    post_title = post.text
    count = post.author.posts.count()
    author = post.author
    author_posts = author.posts.all().count()
    template = "posts/post_detail.html"
    context = {
        "post": post,
        "post_title": post_title,
        "author": author,
        "author_posts": author_posts,
        "form": form,
        "comments": comments,
        "count": count,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """ создание нового поста """
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.method == "POST":
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
    groups = Group.objects.all()
    template = "posts/create_post.html"
    context = {"form": form, "groups": groups}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    """ редактирование поста """
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    groups = Group.objects.all()
    if request.user != author:
        return redirect("posts:post_detail", post_id)
    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None,
    )
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    template = "posts/create_post.html"
    context = {
        "form": form,
        "is_edit": is_edit,
        "post": post,
        "groups": groups,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    """ добавление комментария к посту"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """ Главная страница с постами авторов на кого подписался"""
    post_list = Post.objects.filter(author__following__user=request.user)
    context = pagination(request, post_list)
    template = 'posts/follow.html'
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """ подписаться на автора"""
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """ отписаться от автора """
    Follow.objects.filter(user=request.user,
                          author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}
{{ group.title }}
{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}Редактировать запись{% else %}Добавить запись
            {% endif %}
          </div>
          <div class="card-body">
            {% include 'includes/form.html' %}
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load cache %}
{% block title %}
  Публикации ваших подписок
{% endblock %}

{% block content %}
  <div class="container"><p>
    {% include 'includes/switcher.html' %}
    {% cache 20 index_page %}
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">
          все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  <div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  <article>
    {% for post in page_obj %}
    {% include 'includes/post.html' %}
    <a href="{% url 'posts:group_list' post.group.slug %}">
      все записи группы</a>
    <!-- forloop хранит счётчик цикла и может определять разные состояния
      счётчика -->
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% empty %}
    <p>Если цикл пуст выведется эта строка</p>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
<div class="container py-5">
  <article>
    {% include 'includes/switcher.html' %}
    {% cache 20 index_page %}
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              Все записи группы
            </a>
            {% endif %}
          </li>
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }} ({{ post.author }})
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
              Все посты пользователя ({{ author_posts }})
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if request.user == post.author %}
        <a href="{% url 'posts:post_edit' post.id %}">Редактировать пост</a>
        {% else %}
        <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
        {% endif %}
        {% include 'includes/comments.html' %}
      </article>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }}
    {% if request.user.username != author.username %}
      {% if following %}
        <a class="btn btn-lg btn-light"
           href="{% url 'posts:profile_unfollow' author.username %}"
           role="button"> Отписаться
        </a>
      {% else %}
        <a class="btn btn-lg btn-primary"
           href="{% url 'posts:profile_follow' author.username %}"
           role="button"> Подписаться
        </a>
      {% endif %}
    {% endif %}
    </h1>
    <h3>Всего постов: {{ count }} </h3>
    <article>
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя ({{ count }})</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if request.user == post.author %}
      <a href="{% url 'posts:post_edit' post.id %}">Редактировать пост</a>
      {% else %}
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
      {% endif %}
    </article>
    <br>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">
      Все записи группы "{{ post.group.title }}" </a>
    {% endif %}
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% empty %}
    <p>Постов нет</p>
    {% endfor %}
    <!-- Остальные посты. после последнего нет черты -->
    <!-- Здесь подключён паджинатор -->
    {% include 'posts/includes/paginator.html' %}
  </div>
</main>
{% endblock %}